;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        beginning-of-line-text
        crux-smart-open-line
        helm-M-x
        ns-copy-including-secondary
        sp-backward-barf-sexp
        sp-backward-delete-char
        sp-backward-kill-word
        ))

(setq mc/cmds-to-run-once
      '(
        crux-recentf-find-file
        er-switch-to-previous-buffer
        mouse-set-region
        sp-splice-sexp-killing-backward
        ))
